var testCaseConfig = {
    instaOpsApplicationId: 2,
    applicationUUID: "ebdb7fca-bc07-11e2-8cfd-298ec7bf4fd0",
    organizationUUID: "eb78c65a-bc07-11e2-aae9-41b79935a3f7",
    orgName: "anorgname",
    appName: "sandbox",
    fullAppName: "anorgname_sandbox",
    appOwner: "anon@apigee.com",
    createdDate: 1368475299122,
    lastModifiedDate: 1368475299122,
    monitoringDisabled: false,
    deleted: false,
    googleId: null,
    appleId: null,
    description: null,
    environment: "ug-max-dev",
    customUploadUrl: null,
    defaultAppConfig: {
        lastModifiedDate: null,
        networkMonitoringEnabled: true,
        sessionDataCaptureEnabled: true,
        enableLogMonitoring: true,
        monitorAllUrls: true,
        logLevelToMonitor: 3,
        batteryStatusCaptureEnabled: true,
        obfuscateIMEI: true,
        deviceIdCaptureEnabled: true,
        obfuscateDeviceId: true,
        deviceModelCaptureEnabled: true,
        locationCaptureEnabled: false,
        locationCaptureResolution: 1,
        networkCarrierCaptureEnabled: true,
        enableUploadWhenRoaming: false,
        enableUploadWhenMobile: true,
        agentUploadIntervalInSeconds: 60,
        samplingRate: 100,
        urlRegex: [ ],
        cachingEnabled: false,
        customConfigParameters: [ ],
        appConfigType: "Default",
        imeicaptureEnabled: true
    },
    appConfigOverrideFilters: [ ],
    deviceLevelAppConfig: {
        lastModifiedDate: null,
        networkMonitoringEnabled: true,
        sessionDataCaptureEnabled: true,
        enableLogMonitoring: true,
        monitorAllUrls: true,
        logLevelToMonitor: 3,
        batteryStatusCaptureEnabled: true,
        obfuscateIMEI: true,
        deviceIdCaptureEnabled: true,
        obfuscateDeviceId: true,
        deviceModelCaptureEnabled: true,
        locationCaptureEnabled: false,
        locationCaptureResolution: 1,
        networkCarrierCaptureEnabled: true,
        enableUploadWhenRoaming: false,
        enableUploadWhenMobile: true,
        agentUploadIntervalInSeconds: 60,
        samplingRate: 100,
        urlRegex: [ ],
        cachingEnabled: false,
        customConfigParameters: [ ],
        appConfigType: "Beta",
        imeicaptureEnabled: true
    },
    deviceLevelOverrideEnabled: false,
    deviceTypeAppConfig: {
        lastModifiedDate: null,
        networkMonitoringEnabled: true,
        sessionDataCaptureEnabled: true,
        enableLogMonitoring: true,
        monitorAllUrls: true,
        logLevelToMonitor: 3,
        batteryStatusCaptureEnabled: true,
        obfuscateIMEI: true,
        deviceIdCaptureEnabled: true,
        obfuscateDeviceId: true,
        deviceModelCaptureEnabled: true,
        locationCaptureEnabled: false,
        locationCaptureResolution: 1,
        networkCarrierCaptureEnabled: true,
        enableUploadWhenRoaming: false,
        enableUploadWhenMobile: true,
        agentUploadIntervalInSeconds: 60,
        samplingRate: 100,
        urlRegex: [ ],
        cachingEnabled: false,
        customConfigParameters: [ ],
        appConfigType: "Device",
        imeicaptureEnabled: true
    },
    deviceTypeOverrideEnabled: false,
    deviceNumberFilters: null,
    deviceIdFilters: null,
    deviceModelRegexFilters: null,
    devicePlatformRegexFilters: null,
    networkTypeRegexFilters: null,
    networkOperatorRegexFilters: null,
    abtestingAppConfig: {
        lastModifiedDate: null,
        networkMonitoringEnabled: true,
        sessionDataCaptureEnabled: true,
        enableLogMonitoring: true,
        monitorAllUrls: true,
        logLevelToMonitor: 3,
        batteryStatusCaptureEnabled: true,
        obfuscateIMEI: true,
        deviceIdCaptureEnabled: true,
        obfuscateDeviceId: true,
        deviceModelCaptureEnabled: true,
        locationCaptureEnabled: false,
        locationCaptureResolution: 1,
        networkCarrierCaptureEnabled: true,
        enableUploadWhenRoaming: false,
        enableUploadWhenMobile: true,
        agentUploadIntervalInSeconds: 60,
        samplingRate: 100,
        urlRegex: [ ],
        cachingEnabled: false,
        customConfigParameters: [ ],
        appConfigType: "A/B",
        imeicaptureEnabled: true
    },
    abtestingOverrideEnabled: false,
    abtestingPercentage: 0
}