#!/bin/bash

# we require this shell script to be run from top-level directory of our repo
# so that our DOCSET_TEMPLATE_DIR and SOURCE_DIR paths are correct

# verify that we've been given an argument (the docset directory)
if [ $# -eq 0 ]
then
  echo "Error: Output directory should be passed as argument"
	exit 1
fi

# Output directory is passed in as an argument to this script
OUTPUT_DIR="$1"
echo "OUTPUT_DIR='${OUTPUT_DIR}'"

# Location of html code document, generated by headerdoc2html
DOCUMENT_DIR=${OUTPUT_DIR}/jsdoc/output

# Location of our source code
SOURCE_DIR=../
 
JDDOC_DIR=${SOURCE_DIR}/docs/jsdoc

# Delete old docset and start from fresh, this will kill XCODE if its running.  good for development only, comment out for production.
rm -rf ${OUTPUT_DIR}
 
# Create document directory
mkdir -p ${DOCUMENT_DIR}
 
# Generate html code document for source code.
${JDDOC_DIR}/jsdoc ${SOURCE_DIR}/apigee.js -c sdk_ref_conf.json -d ${DOCUMENT_DIR}

